AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  chatbot-backend

  Example AI chatbot

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 256

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  ChatbotBackendFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: chatbot_backend.app.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      PackageType: Zip
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: UsersTable
        - DynamoDBCrudPolicy:
            TableName:
              Ref: ChatsTable
      Environment:
        Variables:
          USERS_TABLE:
            Ref: UsersTable
          CHATS_TABLE:
            Ref: ChatsTable

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        - AttributeName: source
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
        - AttributeName: stripeCustomerId
          AttributeType: S
        - AttributeName: activeSubscriptionId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1-Email
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2-UsersBySource
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
        - IndexName: GSI3-StripeCustomer
          KeySchema:
            - AttributeName: stripeCustomerId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
              - activeSubscriptionId
              - subscriptionStatus
        - IndexName: GSI4-Subscription
          KeySchema:
            - AttributeName: activeSubscriptionId
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
              - stripeCustomerId
              - subscriptionStatus
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
      RecoveryPeriodInDays: 35

  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Chats
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: chatCreatedAt
          AttributeType: S
        - AttributeName: messageId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1-ChatsByUser
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: chatCreatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - chatId
              - title
              - visibility
              - chatCreatedAt
        - IndexName: GSI2-MessageById
          KeySchema:
            - AttributeName: messageId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: GSI3-MsgsByUser
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - messageId
              - role
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
      RecoveryPeriodInDays: 35

Outputs:
  ChatbotBackendFunctionUrl:
    Description: URL for the Chatbot Backend Lambda function
    Value:
      Fn::GetAtt:
        - ChatbotBackendFunctionUrl
        - FunctionUrl
